[project]
name = "parlamentsdienst-grosserrat-datasette"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "pandas>=2.2.3",
    "pdf-converter",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "717a526a1bbf295302d6a1749ce2a876f4eabfcb" }
pdf-converter = { git = "https://github.com/opendatabs/pdf_converter" }

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
