[project]
name = "parlamentsdienst-grosserrat-datasette"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "pandas>=2.2.3",
    "pdf-converter",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "1a7ec054c92e694f5727ea94f90e6c8f2472aea7" }
pdf-converter = { git = "https://github.com/opendatabs/pdf_converter", rev = "ddeab59ef55cb5643e5b044eda0a8638db97c5ae" }
