[project]
name = "parlamentsdienst-grosserrat-datasette"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "pandas>=2.2.3",
    "pdf-converter",
    "truststore>=0.10.4",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "dfd6ec3541e8506a906b8a0e51f6cf8ac717077e" }
pdf-converter = { git = "https://github.com/opendatabs/pdf_converter", rev = "102ae66408d78cc71a54c0407ed77827d94889e9" }
