[project]
name = "kapo-smileys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "filehash>=0.2.dev1",
    "matplotlib>=3.10.1",
    "more-itertools>=10.6.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyshp>=2.3.1",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
