repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff check
        args: ["--fix"]
      - id: ruff
        name: ruff import sort
        args: ["--select", "I", "--fix"]
        pass_filenames: false
      - id: ruff-format
