[project]
name = "stata-kriminalitaet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "geopandas>=1.0.1",
    "geopy>=2.4.1",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "rapidfuzz>=3.13.0",
    "shapely>=2.1.0",
    "tqdm>=4.67.1",
    "typer>=0.15.4",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "dfd6ec3541e8506a906b8a0e51f6cf8ac717077e" }
