[project]
name = "staka-regierungsratsbeschluesse"
version = "0.1.0"
description = "ETL-job to scrap the Regierungsratsbeschluesse from bs.ch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "common",
    "docling>=2.28.2",
    "markdown>=3.7",
    "pandas>=2.2.3",
    "pdf2image>=1.17.0",
    "pdfkit>=1.0.0",
    "pdfplumber>=0.11.5",
    "pymupdf>=1.25.4",
    "pymupdf4llm>=0.0.18",
    "pypandoc>=1.15",
    "requests>=2.32.3",
    "weasyprint>=65.0",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "v0.1.0" }

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
