[project]
name = "staka-regierungsratsbeschluesse"
version = "0.1.0"
description = "ETL-job to scrap the Regierungsratsbeschluesse from bs.ch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "filehash>=0.2.dev1",
    "more-itertools>=10.6.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
