[project]
name = "staka-regierungsratsbeschluesse"
version = "0.1.0"
description = "ETL-job to scrap the Regierungsratsbeschluesse from bs.ch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "common",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "b2d26f48a7cc43ce823b2763d87c41201e131b40" }


