name: Build Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      base_changed: ${{ steps.process.outputs.base_changed }}
      projects: ${{ steps.process.outputs.projects }}

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          # Use the base branch for PR comparisons
          base: ${{ github.base_ref }}

          # Output a JSON object describing matched filters & changed files
          list-files: json

          # Define all filters: "base" plus each subproject
          filters: |
            base:
              - 'Dockerfile'
            aue_grundwasser:
              - 'Dockerfile'
              - 'aue_grundwasser/**'
            aue_rues:
              - 'Dockerfile'
              - 'aue_rues/**'
            aue_schall:
              - 'Dockerfile'
              - 'aue_schall/**'
            aue_umweltlabor:
              - 'Dockerfile'
              - 'aue_umweltlabor/**'
            awa_feiertage:
              - 'Dockerfile'
              - 'awa_feiertage/**'
            bafu_hydrodaten:
              - 'Dockerfile'
              - 'bafu_hydrodaten/**'
            bafu_hydrodaten_vorhersagen:
              - 'Dockerfile'
              - 'bafu_hydrodaten_vorhersagen/**'
            bvb_fahrgastzahlen:
              - 'Dockerfile'
              - 'bvb_fahrgastzahlen/**'
            dcc_dataspot_schemes:
              - 'Dockerfile'
              - 'dcc_dataspot_schemes/**'
            dcc_ki_faq:
              - 'Dockerfile'
              - 'dcc_ki_faq/**'
            ed_schulferien:
              - 'Dockerfile'
              - 'ed_schulferien/**'
            ed_swisslos_sportfonds:
              - 'Dockerfile'
              - 'ed_swisslos_sportfonds/**'
            esc_faq:
              - 'Dockerfile'
              - 'esc_faq/**'
            euroairport:
              - 'Dockerfile'
              - 'euroairport/**'
            fgi_geodatenshop:
              - 'Dockerfile'
              - 'fgi_geodatenshop/**'
            gd_abwassermonitoring:
              - 'Dockerfile'
              - 'gd_abwassermonitoring/**'
            gd_coronavirus_abwassermonitoring:
              - 'Dockerfile'
              - 'gd_coronavirus_abwassermonitoring/**'
            gva_geodatenshop:
              - 'Dockerfile'
              - 'gva_geodatenshop/**'
            gva_metadata:
              - 'Dockerfile'
              - 'gva_metadata/**'
            ibs_parkhaus_bewegungen:
              - 'Dockerfile'
              - 'ibs_parkhaus_bewegungen/**'
            itbs_klv:
              - 'Dockerfile'
              - 'itbs_klv/**'
            iwb_gas:
              - 'Dockerfile'
              - 'iwb_gas/**'
            iwb_netzlast:
              - 'Dockerfile'
              - 'iwb_netzlast/**'
            jfs_gartenbaeder:
              - 'Dockerfile'
              - 'jfs_gartenbaeder/**'
            kapo_geschwindigkeitsmonitoring:
              - 'Dockerfile'
              - 'kapo_geschwindigkeitsmonitoring/**'
            lufthygiene_rosental:
              - 'Dockerfile'
              - 'lufthygiene_rosental/**'
            luftqualitaet_ch:
              - 'Dockerfile'
              - 'luftqualitaet_ch/**'
            kapo_eventverkehr_stjakob:
              - 'Dockerfile'
              - 'kapo_eventverkehr_stjakob/**'
            kapo_ordnungsbussen:
              - 'Dockerfile'
              - 'kapo_ordnungsbussen/**'
            kapo_smileys:
              - 'Dockerfile'
              - 'kapo_smileys/**'
            meteoblue_rosental:
              - 'Dockerfile'
              - 'meteoblue_rosental/**'
            meteoblue_wolf:
              - 'Dockerfile'
              - 'meteoblue_wolf/**'
            mkb_sammlung_europa:
              - 'Dockerfile'
              - 'mkb_sammlung_europa/**'
            mobilitaet_dtv:
              - 'Dockerfile'
              - 'mobilitaet_dtv/**'
            mobilitaet_mikromobilitaet:
              - 'Dockerfile'
              - 'mobilitaet_mikromobilitaet/**'
            mobilitaet_mikromobilitaet_stats:
              - 'Dockerfile'
              - 'mobilitaet_mikromobilitaet_stats/**'
            mobilitaet_parkflaechen:
              - 'Dockerfile'
              - 'mobilitaet_parkflaechen/**'
            mobilitaet_verkehrszaehldaten:
              - 'Dockerfile'
              - 'mobilitaet_verkehrszaehldaten/**'
            ods_catalog:
              - 'Dockerfile'
              - 'ods_catalog/**'
            ods_harvest:
              - 'Dockerfile'
              - 'ods_harvest/**'
            ods_publish:
              - 'Dockerfile'
              - 'ods_publish/**'
            ods_update_temporal_coverage:
              - 'Dockerfile'
              - 'ods_update_temporal_coverage/**' 
            parkendd:
              - 'Dockerfile'
              - 'parkendd/**'
            parkhaeuser:
              - 'Dockerfile'
              - 'parkhaeuser/**'
            parlamentsdienst_gr_abstimmungen:
              - 'Dockerfile'
              - 'parlamentsdienst_gr_abstimmungen/**'
            parlamentsdienst_grosserrat:
              - 'Dockerfile'
              - 'parlamentsdienst_grosserrat/**'
            parlamentsdienst_grosserrat_datasette:
              - 'Dockerfile'
              - 'parlamentsdienst_grosserrat_datasette/**'
            smarte_strasse_ladestation:
              - 'Dockerfile'
              - 'smarte_strasse_ladestation/**'
            stadtreinigung_sauberkeitsindex:
              - 'Dockerfile'
              - 'stadtreinigung_sauberkeitsindex/**'
            stadtreinigung_wildedeponien:
              - 'Dockerfile'
              - 'stadtreinigung_wildedeponien/**'
            staka_abstimmungen:
              - 'Dockerfile'
              - 'staka_abstimmungen/**'
            staka_baupublikationen:
              - 'Dockerfile'
              - 'staka_baupublikationen/**'
            staka_briefliche_stimmabgaben:
              - 'Dockerfile'
              - 'staka_briefliche_stimmabgaben/**'
            staka_kandidaturen:
              - 'Dockerfile'
              - 'staka_kandidaturen/**'
            staka_kantonsblatt:
              - 'Dockerfile'
              - 'staka_kantonsblatt/**'
            staka_regierungsratsbeschluesse:
              - 'Dockerfile'
              - 'staka_regierungsratsbeschluesse/**'
            staka_staatskalender:
              - 'Dockerfile'
              - 'staka_staatskalender/**'
            stata_befragungen:
              - 'Dockerfile'
              - 'stata_befragungen/**'
            stata_bik:
              - 'Dockerfile'
              - 'stata_bik/**'
            stata_daily_upload:
              - 'Dockerfile'
              - 'stata_daily_upload/**'
            stata_gwr:
              - 'Dockerfile'
              - 'stata_gwr/**'
            stata_hunde:
              - 'Dockerfile'
              - 'stata_hunde/**'
            stata_parzellen:
              - 'Dockerfile'
              - 'stata_parzellen/**'
            stata_harvester:
              - 'Dockerfile'
              - 'stata_harvester/**'
            stata_pull_changes:
              - 'Dockerfile'
              - 'stata_pull_changes/**'
            tba_abfuhrtermine:
              - 'Dockerfile'
              - 'tba_abfuhrtermine/**'
            tba_baustellen:
              - 'Dockerfile'
              - 'tba_baustellen/**'
            tba_sprayereien:
              - 'Dockerfile'
              - 'tba_sprayereien/**'
            tba_wiese:
              - 'Dockerfile'
              - 'tba_wiese/**'
            zefix_handelsregister:
              - 'Dockerfile'
              - 'zefix_handelsregister/**'
            zrd_gesetzessammlung:
              - 'Dockerfile'
              - 'zrd_gesetzessammlung/**'
      - name: Process changes
        id: process
        run: |
          CHANGES='${{ steps.filter.outputs.changes }}'
          echo "Detected changes = $CHANGES"

          if [[ "$CHANGES" == *"base"* ]]; then
            echo "base_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "base_changed=false" >> "$GITHUB_OUTPUT"
          fi

          CLEAN_CHANGES=$(echo "$CHANGES" | jq -c 'map(select(. != "base"))')

          echo "projects=$CLEAN_CHANGES" >> "$GITHUB_OUTPUT"
          
  # --------------------------------------------------------------
  # Build/push the base image if needed
  # --------------------------------------------------------------
  build_base:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push the base image
        # Only run if base_changed == 'true'
        if: ${{ needs.changes.outputs.base_changed == 'true' }}
        uses: docker/build-push-action@v6
        with:
          # Build from the repository root
          context: .
          file: ./Dockerfile
          # Only push on merges to master or manual triggers
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch' }}
          tags: |
            ghcr.io/${{ github.repository }}/base:${{ github.sha }}
            ${{ (
                  (github.event_name == 'push' && github.ref == 'refs/heads/master')
                  || github.event_name == 'workflow_dispatch'
               ) && format('ghcr.io/{0}/base:latest', github.repository)
               || ''
            }}
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

  # --------------------------------------------------------------
  # Build all subprojects
  # --------------------------------------------------------------
  build_and_push:
    needs: [changes, build_base]
    if: ${{ needs.changes.outputs.projects != '[]' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push Docker image for ${{ matrix.project }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.project }}
          file: ./${{ matrix.project }}/Dockerfile
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.project }}:${{ github.sha }}
            ${{ (
                  (github.event_name == 'push' && github.ref == 'refs/heads/master')
                  || github.event_name == 'workflow_dispatch'
               ) && format('ghcr.io/{0}/{1}:latest', github.repository, matrix.project)
               || ''
            }}
          cache-from: type=gha,scope=${{ matrix.project }}
          cache-to: type=gha,mode=max,scope=${{ matrix.project }}
