name: Build Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      base_changed: ${{ steps.process.outputs.base_changed }}
      projects: ${{ steps.process.outputs.projects }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          # Use the base branch for PR comparisons
          base: ${{ github.base_ref }}

          # Output a JSON object describing matched filters & changed files
          list-files: json

          # Define all filters: "base" plus each subproject
          filters: |
            base:
              - 'Dockerfile'
              - 'common/*'
              - 'ods_publish/*'
            dataspot:
              - 'dataspot/*'
            jfs_gartenbaeder:
              - 'jfs_gartenbaeder/*'
            kapo_geschwindigkeitsmonitoring:
              - 'kapo_geschwindigkeitsmonitoring/*'
            kapo_smileys:
              - 'kapo_smileys/*'
            meteoblue_rosental:
              - 'meteoblue_rosental/*'
            mobilitaet_dtv:
              - 'mobilitaet_dtv/*'
            mobilitaet_mikromobilitaet:
              - 'mobilitaet_mikromobilitaet/*'
            mobilitaet_mikromobilitaet_stats:
              - 'mobilitaet_mikromobilitaet_stats/*'
            mobilitaet_verkehrszaehldaten:
              - 'mobilitaet_verkehrszaehldaten/*'
            staka_regierungsratsbeschluesse:
              - 'staka_regierungsratsbeschluesse/*'
            stata_harvester:
              - 'stata_harvester/*'

      - name: Process changes
        id: process
        run: |
          CHANGES='${{ steps.filter.outputs.changes }}'
          echo "Detected changes = $CHANGES"

          if [[ "$CHANGES" == *"base"* ]]; then
            echo "base_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "base_changed=false" >> "$GITHUB_OUTPUT"
          fi

          # **Also** set `projects` to the same JSON array so the matrix can read it
          echo "projects=$CHANGES" >> "$GITHUB_OUTPUT"

  # --------------------------------------------------------------
  # Build/push the base image if needed
  # --------------------------------------------------------------
  build_base:
    needs: changes
    # Only run if base_changed == 'true'
    if: ${{ needs.changes.outputs.base_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push the base image
        uses: docker/build-push-action@v5
        with:
          # Build from the repository root
          context: .
          file: ./Dockerfile
          # Only push on merges to master or manual triggers
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch' }}
          tags: |
            ghcr.io/${{ github.repository }}/base:${{ github.sha }}
            ${{ (
                  (github.event_name == 'push' && github.ref == 'refs/heads/master')
                  || github.event_name == 'workflow_dispatch'
               ) && format('ghcr.io/{0}/base:latest', github.repository)
               || ''
            }}
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

  # --------------------------------------------------------------
  # Build all subprojects
  # --------------------------------------------------------------
  build_and_push:
    # Wait for both 'changes' job to complete AND 'build_base' job to complete/skip
    needs: [changes, build_base]
    # Only run if 'projects' is not an empty array
    if: ${{ needs.changes.outputs.projects != '[]' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push Docker image for ${{ matrix.project }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.project }}
          file: ./${{ matrix.project }}/Dockerfile
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.project }}:${{ github.sha }}
            ${{ (
                  (github.event_name == 'push' && github.ref == 'refs/heads/master')
                  || github.event_name == 'workflow_dispatch'
               ) && format('ghcr.io/{0}/{1}:latest', github.repository, matrix.project)
               || ''
            }}
          cache-from: type=gha,scope=${{ matrix.project }}
          cache-to: type=gha,mode=max,scope=${{ matrix.project }}
